modLoader = "javafml"
loaderVersion = "[36,)"

issueTrackerURL = "https://github.com/Hexicube/Spice-of-Life-Carrot-Edition/issues"
displayURL = "https://curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition"
logoFile = "logo 160.png"
license = "LGPL-2.1"
credits = "Lewis_McReu for some coding assistance, Vik for the great new art :)"
authors = "Cazsius, Talonos, juliand665, Hexicube"

[[mods]] # no need to indent — we only have one mod anyway

modId = "solapple"
version = "${file.jarVersion}"
displayName = "Spice of Life: Apple Edition"
description = '''
A mod designed to encourage dietary variety!

It does so by rewarding the player for eating a variety of foods instead of punishing them for failing to diversify.
Instead of using the stick, we use the apple!

This version makes use of "food groups", granting hearts for eating a full set of food.
This version is based on Carrot edition, which grants hearts for reaching milestones of eaten unique foods.
'''

# Dependencies are optional.
[[dependencies.solapple]]
	modId = "forge"
	mandatory = true
	versionRange = "[36,)"
	ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
	side = "BOTH" # BOTH, CLIENT or SERVER
